/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sergo.stringmetric;

import org.junit.Test;
import static org.junit.Assert.*;

public class StringMetricTest {
    @Test public void testAppHasAGreeting() {
        AppLauncher classUnderTest = new AppLauncher();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
